### PR TITLE
Removes Template Web Browser

### PR DESCRIPTION
**Pull request by redreceipt**
Screen Shot 2020-03-30 at 3 05 42 PM

### CODE REVIEW

**Comment by redreceipt** [comment]
I can't link to test this. Once I confirm, I'll mark this ready.

**Comment by redreceipt** [comment]
These tests aren't going to pass until the `ui-connected` web view makes it into a production release

**Comment by FrankGrand** [comment]
@redreceipt @conrad-vanl Anything we need to do to move this forward?

**Comment by conrad-vanl** [comment]
@redreceipt if you point this PR to the Develop branch I think we can figure out how to get it merged.  There are conflicts now though, so please make sure this is still relevant.

**Comment by conrad-vanl** [comment]
This pull request is being closed to clear out "backlog" post cycle ending. You can push to have it reprioritized in a future cycle or re-open once changes have been made and it is ready for review.

**Pull request closed without merging**
