### PR TITLE
Update react-native-geolocation-service

### PR DESCRIPTION
**Pull request by vinnyjth**
**IMPORTANT: If this is for testing code in our npm dependencies, you should be pointing your PR at the `canary` or `next` branch. `master` should never rely on unreleased code.**

### CODE REVIEW

**Comment by vinnyjth** [comment]
Should be merged with: https://github.com/ApollosProject/apollos-apps/pull/1671

**Comment by redreceipt** [comment]
tested, works good, I approved the apps PR

this one is blocked until we either point this at canary (and also make sure canary is caught up) before we merge or just bump master to the canary versions.

**Comment by vinnyjth** [comment]
@redreceipt Done here 👍

**Comment by redreceipt** [comment]
I love it. but it does beg the question...

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
