### PR TITLE
remove dummy suggested follows

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Review by vinnyjth — CHANGES_REQUESTED** [review]
any chance you could leave these in but comment them out? or use fake emails? since this option is handy but not documented anywhere else

**Comment by redreceipt** [comment]
> any chance you could leave these in but comment them out? or use fake emails? since this option is handy but not documented anywhere else

what if I write a simple markdown doc and drop it in?

**Comment by vinnyjth** [comment]
> > any chance you could leave these in but comment them out? or use fake emails? since this option is handy but not documented anywhere else
> 
> what if I write a simple markdown doc and drop it in?

Sounds fantastic. Might be nice if we could have a `config.yml.md` that documented all of the important/confusing variables

**Comment by redreceipt** [comment]
yes that's a good idea. I'll start one where we can drop documentation for any of the variables that need it

**Comment by redreceipt** [comment]
ok @vinnyjth take a look

**Comment by vinnyjth** [comment]
stellar !

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
