### PR TITLE
Adds Splash and Icon Generation Scripts

### PR DESCRIPTION
**Pull request by redreceipt**
MAJOR WIN! This allows us to automatically generate icons and splash screens with a command:

```
yarn icons <file>
yarn splash <file>
```

I had to move us from `react-native-bootsplash` to `react-native-splash-screen`

**IMPORTANT: If this is for testing code in our npm dependencies, you should be pointing your PR at the `canary` or `next` branch. `master` should never rely on unreleased code.**

### CODE REVIEW

**Comment by vinnyjth** [comment]
I really hate to say this, and I don't think this invalidates this PR, but we technically have support for this already with `yarn generate-bootsplash`. I think it works a little differently, it pulls from that `assets` folder, but it has the advantage of not needing further native code changes to get it working.

**Comment by redreceipt** [comment]
Yea I don't love the number of native code changes but with this package, we get icons and splash. plus the splash generation with this package is WAY easier. The former has you answer a bunch of questions and you have to name the file correctly.

**Comment by redreceipt** [comment]
plus no assets folder required

**Comment by vinnyjth** [comment]
That's enough to sell me @redreceipt, but I vote we point this at the `next` branch. I would rather slip all our native changes together.

**Comment by redreceipt** [comment]
> plus no assets folder required

for images that is

**Comment by redreceipt** [comment]
moved it to `next`. what do you think the timeline on 2.0 is? like do you think we'll onboard any more churches with 1.x? If so, I'll need to document how to generate icons and splash the old fashioned way for those churches.

**Comment by vinnyjth** [comment]
@redreceipt Conrad and I talked about this for allittle bit. It's probably something we'll wrap up for the Holidays (so I'm assuming not the next cycle, but the one after). It's hard to say at this point if we will onboard any churches onto 1.x though, at this point I think we could probably count on onboarding new churches onto an beta 2.x build.

**Comment by vinnyjth** [comment]
@redreceipt for our current version, you could link out to the official docs: 

https://github.com/zoontek/react-native-bootsplash#setup

**Comment by redreceipt** [comment]
@vinnyjth still good with this one?

**Comment by vinnyjth** [comment]
@redreceipt yah. looks good to me. I haven't tested but I'll approve

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
