### PR TITLE
Feature fragments

### PR DESCRIPTION
**Pull request by vinnyjth**

### CODE REVIEW

**Comment by vinnyjth** [comment]
I don’t think I’ll be able to get them to pass until the core PR is merged. Might be a workaround though

**Comment by burkeshartsis** [comment]
I merged the PR on core already. I tried to run them locally and they still failed.

**Comment by vinnyjth** [comment]
Linked or unlinked? They won’t work in Github Actions until a release is done :/ if the failures are what I expect I think we can copy the right fragments in maybe

**Comment by vinnyjth** [comment]
@burkeshartsis can you please approve this PR?

**Pull request merged**
