### PR TITLE
Adds content feature feed

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Comment by redreceipt** [comment]
blocked until canary packages are in

**Comment by redreceipt** [comment]
something is messed up. I can't merge in the current canary branch code, the `<Discover />` component doesn't reflect the latest changes into this PR.

**Comment by vinnyjth** [comment]
@redreceipt are you sure you're not linked? Do you think it's a publishing issue on `apps`?

**Comment by redreceipt** [comment]
looks like github didn't merge properly when you hit that button earlier

**Comment by vinnyjth** [comment]
oh weird

**Comment by redreceipt** [comment]
this one is ready, just needs your approval

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
