### PR TITLE
removes wordmark by default

### PR DESCRIPTION
**Pull request by redreceipt**
removing this from the default because it's very straigtforward to add back and it's something that looks fine with or without

### CODE REVIEW

**Comment by conrad-vanl** [comment]
What if we put the logo source files into the theme? And then you could get to template zero by porting this code over into -apps?

**Comment by redreceipt** [comment]
so export jpgs by default?

**Comment by conrad-vanl** [comment]
The theme would just have a value like:

```
brand: {
  fullLogo: require('../path/to/logo'),
  ...anyOtherBrandImages
}
```

and the default `brand` would use the Apollos Logo

**Comment by vinnyjth** [comment]
I like what @conrad-vanl is suggesting

**Comment by redreceipt** [comment]
What if the default was just an SVG exported from icons and it worked exactly like the `BrandIcon` on the landing page?

**Comment by conrad-vanl** [comment]
I don't think I'm opposed to that. Only problem with our Icons is that they're single color only, and I think most of our church logos are multi color. Not all of them though....it would make dark/light mode support easier.

**Comment by redreceipt** [comment]
Oh, I didn't think about colors. I was mainly challenging the notion that it needs to be in there at all by default. But I'll table this for now.

**Comment by nlewis84** [comment]
VCC has a multi color wordmark that stays the same for dark and light mode.

**Pull request closed without merging**
