### PR TITLE
Removes ESLint

### PR DESCRIPTION
**Pull request by redreceipt**
**IMPORTANT: If this is for testing code in our npm dependencies, you should be pointing your PR at the `canary` or `next` branch. `master` should never rely on unreleased code.**

### CODE REVIEW

**Comment by redreceipt** [comment]
ah, nohoist is killing this...

**Comment by redreceipt** [comment]
@vinnyjth is there a reason we are nohoist'ing everything or could we just do the packages we know cause problems?

**Comment by vinnyjth** [comment]
@redreceipt The packages that cause problem list turns out to be very long. Easier to no hoist everything. Also stops us from having problems that don't surface when you're hoisting, but our clients run into when they aren't hoisting.

**Comment by redreceipt** [comment]
gotcha, I suppose I could just put apollos/eslint config at the root

**Comment by redreceipt** [comment]
nope that didn't work

**Pull request closed without merging**
