### PR TITLE
Testing Panel - Following List

### PR DESCRIPTION
**Pull request by tomthornton**

### CODE REVIEW

**Comment by redreceipt** [comment]
@tomthornton you still need this follow list in the testing panel?

**Comment by tomthornton** [comment]
@redreceipt not sure. are we planning on implementing this?

**Comment by redreceipt** [comment]
If you don't care either, I'd opt to leave it out. Figured you had a reason for submitting.

**Comment by tomthornton** [comment]
@redreceipt this was one of my first PRs. I think we should revisit it later and discuss some design changes

**Comment by redreceipt** [comment]
yep I agree, sounds good

**Pull request closed without merging**
