### PR TITLE
Master > Next

### PR DESCRIPTION
**Pull request by redreceipt**
**IMPORTANT: If this is for testing code in our npm dependencies, you should be pointing your PR at the `canary` or `next` branch. `master` should never rely on unreleased code.**

### CODE REVIEW

**Review by vinnyjth — APPROVED** [review]

**Comment by vinnyjth** [comment]
I think you're fine to merge this with or without tests passing (but I'm curious if they pass)

**Comment by redreceipt** [comment]
> I think you're fine to merge this with or without tests passing (but I'm curious if they pass)

me too

**Comment by redreceipt** [comment]
well would you look at that...

**Comment by vinnyjth** [comment]
I feel like we should get a badge for that

**Pull request merged**
