### PR TITLE
v1.6.0-beta.0

### PR DESCRIPTION
**Pull request by redreceipt**
**IMPORTANT: If this is for testing code in our npm dependencies, you should be pointing your PR at the `canary` or `next` branch. `master` should never rely on unreleased code.**

### CODE REVIEW

**Comment by redreceipt** [comment]
we should catch develop up to master and then delete it. but first, we'll need to do a stable release with all the new "Node" stuff in it

**Comment by vinnyjth** [comment]
So the "correct" way to do this is in a release PR :)

**Comment by redreceipt** [comment]
> So the "correct" way to do this is in a release PR :)

I figured. that's why I marked it blocked. Can't merge this until we have a stable 1.6.0 to point master to. That's still the part of our whole process I'm fuzzy on because I haven't walked through it myself yet.

**Comment by redreceipt** [comment]
@vinnyjth are you expecting me to just merge this in?

**Comment by vinnyjth** [comment]
Yep! After tests pass, go for it.

**Pull request merged**
