### PR TITLE
Updates to new church online enpoint

### PR DESCRIPTION
**Pull request by redreceipt**
**IMPORTANT: Unless you are doing a release, you should be pointing your PR at the `develop` branch. `master` should not rely on code not published in `npm`**

### CODE REVIEW

**Comment by redreceipt** [comment]
blocked until new church online code is released

**Review by vinnyjth — APPROVED** [review]
I believe this is GTG now

**Comment by redreceipt** [comment]
i'd rather wait until it's in a release so we can point master to it

**Comment by redreceipt** [comment]
it's just to get the API to stop throwing errors on heroku

**Comment by vinnyjth** [comment]
How about we get it into `develop` so we can have the change locally?

**Comment by vinnyjth** [comment]
It will end up `master` automatically post release that way

**Pull request merged**
