### PR TITLE
feat: Conslidate down to node-single and remove ContentSingle. 

### PR DESCRIPTION
**Pull request by vinnyjth**
**IMPORTANT: If this is for testing code in our npm dependencies, you should be pointing your PR at the `canary` or `next` branch. `master` should never rely on unreleased code.**

### CODE REVIEW

**Comment by redreceipt** [comment]
❤️❤️❤️

**Comment by redreceipt** [comment]
home tab won't load for me
Screen Shot 2020-12-11 at 8 21 44 AM

and is this how the devo is supposed to look?

Screen Shot 2020-12-11 at 8 22 19 AM

**Comment by vinnyjth** [comment]
Simulator Screen Shot - iPhone 11 - 2020-12-11 at 10 25 44
Simulator Screen Shot - iPhone 11 - 2020-12-11 at 10 25 34

**Comment by vinnyjth** [comment]
@redreceipt This is ready to look at again. Make sure to pull on both `apps` and `templates`

**Comment by redreceipt** [comment]
needs a _liiiiiitle_ more spacing on the bottom because of the modal

Screen Shot 2020-12-11 at 12 07 07 PM

**Review by redreceipt — CHANGES_REQUESTED** [review]
bottom of devo view needs a little more spacing, see comment in PR

**Comment by vinnyjth** [comment]
@redreceipt Weird - I'm getting different results than you irt the spacing. I'll pull again and take another look.

**Comment by vinnyjth** [comment]
simulator_screenshot_1A3E9858-A9C0-44E8-951F-52C3B0E0B2F3

**Comment by vinnyjth** [comment]
simulator_screenshot_BCE10E90-E659-4F24-B6F5-FDA6E4705847

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
