### PR TITLE
Removes Root URL from Config

### PR DESCRIPTION
**Pull request by redreceipt**
doesn't look like we need it

**IMPORTANT: Unless you are doing a release, you should be pointing your PR at the `develop` branch. `master` should not rely on code not published in `npm`**

### CODE REVIEW

**Comment by vinnyjth** [comment]
https://github.com/ApollosProject/apollos-apps/blob/master/packages/apollos-data-connector-passes/src/resolver.js#L66-L67

**Comment by redreceipt** [comment]
haha dang...

**Comment by vinnyjth** [comment]
Yahhh... I would advocate for consolidating this field or/and adding better comments to this whole file.

**Comment by redreceipt** [comment]
> Yahhh... I would advocate for consolidating this field or/and adding better comments to this whole file.

Explain what you mean. I feel like there should be a way to pull that base URL built into Apollo Server...

**Comment by vinnyjth** [comment]
@redreceipt I was assuming that there were a few more parts of our API that use a similar field (like universal linking) but a glance, I guess not. 

Maybe we could rename this field to be more specific to the `PASS` feature?

**Comment by vinnyjth** [comment]
There's not a default way to get an app's domain name from inside Heroku, if that's what you were thinking.

**Comment by redreceipt** [comment]
yea I like that

**Pull request closed without merging**
