### PR TITLE
locks down node version

### PR DESCRIPTION
**Pull request by redreceipt**
were having podfile lock changes on build, I'm guessing it's the node version but I haven't confirmed

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt It's because we are updating the `npm` version of our media player package, which bumps the `pod` version of that package. Except we aren't capturing the `podfile.lock` changes w/ our `bump` tool.

**Comment by redreceipt** [comment]
I recently updated the podfile lock https://github.com/ApollosProject/apollos-templates/commit/257452ed3cb5f5d861aafde8204e5fbc82ef1e18 and it didn't help

**Comment by redreceipt** [comment]
our bump tool does run `yarn` which includes `yarn pods`

**Comment by redreceipt** [comment]
https://github.com/ApollosProject/apollos-templates/blob/42224bd8ea83de16915a82faa9ec2e968b9884d6/scripts/bump.sh#L29

**Comment by vinnyjth** [comment]
Weird, I see what you're saying and you're correct. And it's the GLOG version that's changing. Merging this seems like a good move.

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
