### PR TITLE
remove redundant typemap declaration

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Comment by vinnyjth** [comment]
I would merge this without a glance - but we are using the fact that these are separate bits on NS to have fine control over loading states - https://github.com/NewSpring/corinth/blob/master/loadConfig.js#L26

We need to find a better solution for what NS is forced to do before we can merge these.

**Comment by redreceipt** [comment]
They could do the same thing, just spread in the type map from core and then overwrite those two, right?

**Comment by vinnyjth** [comment]
@redreceipt That would break the `cache.js` file. We need the `cache.js` to be `fragmentTypes.json `and `ApollosConfig.TYPE_MAP` to be just override.

**Comment by vinnyjth** [comment]
The better path might be to fix the loading state guesser so we don't need that override to begin with. Not sure we can though with our current schema.

**Comment by redreceipt** [comment]
Oh shoot

**Comment by redreceipt** [comment]
blocked on release

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
