### PR TITLE
Create a map of types to interfaces and include in Config

### PR DESCRIPTION
**Pull request by jimmyhogoboom**
**IMPORTANT: If this is for testing code in our npm dependencies, you should be pointing your PR at the `canary` or `next` branch. `master` should never rely on unreleased code.**

Creates a map of types to their interfaces and includes them in the ApollosConfig. Added to support https://github.com/ApollosProject/apollos-apps/pull/1728

### CODE REVIEW

**Comment by vinnyjth** [comment]
@redreceipt This is a required step in upgrading to 2.0.1 btw

**Review by vinnyjth — APPROVED** [review]

**Comment by redreceipt** [comment]
what do you mean "required" like a breaking change?

**Comment by vinnyjth** [comment]
Yah, you will see errors in your app without it.

**Comment by vinnyjth** [comment]
Which means that 2.0.1 should probably be 2.1.0

**Comment by redreceipt** [comment]
is there a way we can make the apps change non-breaking before releasing 2.0.1? or else technically it belongs in v3 right?

**Pull request merged**
