### PR TITLE
React navigation v5

### PR DESCRIPTION
**Pull request by conrad-vanl**
**should be merged into a 2.0 or next branch**

https://github.com/ApollosProject/apollos-apps/pull/1508

### CODE REVIEW

**Comment by conrad-vanl** [comment]
Closing, read ApollosProject/apollos-apps#1508 for more info

**Comment by redreceipt** [comment]
currently stumped here
Screen Shot 2020-11-04 at 4 27 48 PM

**Comment by redreceipt** [comment]
blocked on apps PR making through to the 2.0-alpha channel

**Comment by redreceipt** [comment]
@vinnyjth this one is ready to test linked to the 2.0 versions. I'm not sure why the test is failing on the CI, it passes locally. Says it's still looking for `react-navigation` for some reason.

Screen Shot 2020-11-06 at 9 18 07 AM

**Comment by vinnyjth** [comment]
@redreceipt Do we have `2.0-alpha` versions we can update this PR to point at?

**Comment by redreceipt** [comment]
haha I updated them and forgot to push 😅

**Comment by vinnyjth** [comment]
Not sure if this is worth solving - but cards without images but with Media look really funky. 

image

**Comment by vinnyjth** [comment]
The modal view on Android doesn't look great :/ 

image

**Comment by vinnyjth** [comment]
The PR looks great :D I noted two style issues I ran into above. I think the Android one is worth solving, but it's up to you if you want to do it here or in a future PR. The one w/ a missing cover image isn't as big of a deal, because content items w/ out cover images already look bad, now they just look worse.

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
