### PR TITLE
People datasource

### PR DESCRIPTION
**Pull request by vinnyjth**

### CODE REVIEW

**Review by jimmyhogoboom — APPROVED** [review]
This is a really cool PR. I was wondering how we were gonna straddle the line between Rock and Postgres, and this is a very clever way to do it. 

I can't figure out why the CI health check is failing though. Everything is running fine on my end.

**Comment by vinnyjth** [comment]
@jimmyhogoboom Thanks :D ci-health checking is failing while the `apps` branch is unmerged. As soon as we merge the `apps` branch, we can point this branch at the `canary` build and we'll be good.

**Comment by vinnyjth** [comment]
@jimmyhogoboom I've updated the canary packages so our health check is working again

**Review by jimmyhogoboom — APPROVED** [review]
Nice, looks good!

**Pull request merged**
