### PR TITLE
Makes PORT variable optional

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Comment by vinnyjth** [comment]
At one point I think we had this a specific way for tests that were importing files from the API. I believe that is no longer the case, but maybe run the tests to confirm.

**Comment by redreceipt** [comment]
There are no tests in the API template

—
Michael

**Comment by vinnyjth** [comment]
> There are no tests in the API template

It was the app tests that were importing from the API. I think we fixed that though.

**Comment by redreceipt** [comment]
I'm sorry I'm confused. Not sure what I need to do here.

**Pull request merged**
